# Generated by Django 5.1.2 on 2024-10-30 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wojewodztwo', models.CharField(choices=[('dolnośląskie', 'Dolnośląskie'), ('kujawsko-pomorskie', 'Kujawsko-Pomorskie'), ('lubelskie', 'Lubelskie'), ('lubuskie', 'Lubuskie'), ('łódzkie', 'Łódzkie'), ('małopolskie', 'Małopolskie'), ('mazowieckie', 'Mazowieckie'), ('opolskie', 'Opolskie'), ('podkarpackie', 'Podkarpackie'), ('podlaskie', 'Podlaskie'), ('pomorskie', 'Pomorskie'), ('śląskie', 'Śląskie'), ('świętokrzyskie', 'Świętokrzyskie'), ('warmińsko-mazurskie', 'Warmińsko-Mazurskie'), ('wielkopolskie', 'Wielkopolskie'), ('zachodniopomorskie', 'Zachodniopomorskie')], max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
