# Generated by Django 5.1.2 on 2024-11-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='wojewodztwo',
            field=models.CharField(choices=[('PL-DS', 'Dolnośląskie'), ('PL-KP', 'Kujawsko-Pomorskie'), ('PL-LU', 'Lubelskie'), ('PL-LB', 'Lubuskie'), ('PL-LD', 'Łódzkie'), ('PL-MA', 'Małopolskie'), ('PL-MZ', 'Mazowieckie'), ('PL-OP', 'Opolskie'), ('PL-PK', 'Podkarpackie'), ('PL-PD', 'Podlaskie'), ('PL-PM', 'Pomorskie'), ('PL-SL', 'Śląskie'), ('PL-SK', 'Świętokrzyskie'), ('PL-WN', 'Warmińsko-Mazurskie'), ('PL-WP', 'Wielkopolskie'), ('PL-ZP', 'Zachodniopomorskie')], max_length=32),
        ),
    ]
