# Generated by Django 5.1.2 on 2024-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapka', '0002_alter_userinfo_wojewodztwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='plec',
            field=models.CharField(choices=[('m', 'mężczyzna'), ('k', 'kobieta')], default='m', max_length=32),
            preserve_default=False,
        ),
    ]
