# Generated by Django 5.1.2 on 2024-11-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapka', '0003_userinfo_plec'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='clickCount',
            field=models.IntegerField(default=0),
        ),
    ]
